### ISSUE TITLE
When both iOS & Android Xamrin SDK's are released combinedly, android SDK wasn't compiling.

### ISSUE THREAD

**Issue by SailathaG** [JudoPay/Judo-Xamarin#12]
When both iOS &amp; Android Xamrin SDK's are released combinedly, android SDK wasn't compiling.

https://reports3.testuff.com/view/Judo-Pay-uzemytq42zjbn7vfncctlvrruoqjucyp/run/c8d2320c6a32ba1e4b4393b5ce707967/

System information: 
freeDisk: 264.0
os: Windows 7 Professional
cpu: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
totalRam: 4095.0
freeRam: 4095.0

 
Severity: P2 - High

Branch: 1.0
Project: Xamarin Android SDK

Test summary: Xamarin Android SDK

Report defect as closed: https://service3.testuff.com/api/v0/status/Judo-Pay-uzemytq42zjbn7vfncctlvrruoqjucyp/d8cf956dd42c7aca6fae24b0af3caa10/?status=closed

**Comment by himanshuatjudo** [comment]
There was Serilog reference issue in android xamarin sample app, it is fixed now.
