### ISSUE TITLE
Exception after clicking on "Pay" in JudoPay Page. Xamarin.Forms iOS

### ISSUE THREAD

**Issue by po0kie** [JudoPay/Judo-Xamarin#45]
All works fine until I click "pay" in the step after credit card numbers, Country and ZipCode.
When I click on "Pay" it rhwos exception with the following stack

  at JudoDotNetXamariniOSSDK.Views.CreditCardView.MakePayment () [0x00055] in <filename unknown>:0 
  at JudoDotNetXamariniOSSDK.Views.CreditCardView.<ViewDidLoad>m__1 (System.Object sender, System.EventArgs ev) [0x00000] in <filename unknown>:0 
  at UIKit.UIControlEventProxy.Activated () [0x00007] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/src/UIKit/UIControl.cs:38 
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, IntPtr principal, IntPtr delegate) [0x00005] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/src/UIKit/UIApplication.cs:63 
  at WhatsOn.iOS.Application.Main (System.String[] args) [0x00002] in C:\VS2013\Projects\Marc\Xamarin\WhatsOn\WhatsOn\WhatsOn.iOS\Main.cs:19 

Any idea where to look for?

Best regards
Marc

**Comment by LukeFieldsend** [comment]
Hello Marc, 
Thanks for getting in contact

Could you please provide with the exception type and message as well as details about your inputs. Obviously not card numbers but type of card (visa,Amex), type of payment could be helpful  and I'll try and recreate the issue.


cheers 
Luke

**Comment by po0kie** [comment]
Hi Luke,

Mode = Sandbox
The Type of card: Sandbox cards of the account.
Tried with all sandbox card (except declined cards)

CARD TYPE
Visa credit
Visa debit
Mastercard credit


Country: UK / Other (tried with these 2)
ZipCode: 07005

Payment: Normal Payment (Not PreAuth, or anything…just a normal payment)
Currency: EUR
Amount: 4,00


From where we call the Payment:
MasterDetail -> PushPage -> PushPage -> PushModal -> call the DependencyService<IPlatform> for the JudoPay

    public void MakeJudoPayment(decimal amount, string currency, string consumerReference, string paymentReference, string itemId
      JudoSuccessCallback successCallback, JudoFailureCallback failureCallback)
    {

      Dictionary<string, string> dictionary =
      new Dictionary<string, string>();

      dictionary.Add("paymentItemId", Guid.NewGuid().ToString());
      dictionary.Add("itemId", itemId );

      var paymentViewModel = new PaymentViewModel
      {
        Amount = 4.5m,
        ConsumerReference = consumerReference,
        YourPaymentMetaData = dictionary,
        Currency = currency,
        Card = new CardViewModel()
      };

      try
      {
        Judo.Instance.Payment(paymentViewModel, successCallback, failureCallback);
      }
      catch (Exception ex)
      {

      }

    }

Exception:

{System.TypeInitializationException: The type initializer for 'JudoDotNetXamariniOSSDK.Controllers.LoadingScreen' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at JudoDotNetXamariniOSSDK.Controllers.LoadingScreen..cctor () [0x00011] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at JudoDotNetXamariniOSSDK.Views.CreditCardView.MakePayment () [0x00011] in <filename unknown>:0 }


Source:
JudoDotNetXamariniOSSDK

StackTrace:
"  at JudoDotNetXamariniOSSDK.Views.CreditCardView.MakePayment () [0x00011] in <filename unknown>:0 "                string


Inner Exception:
Message "Object reference not set to an instance of an object"


Best regards
Marc



De: Luke Fieldsend [mailto:notifications@github.com]
Enviado el: viernes, 22 de julio de 2016 12:23
Para: JudoPay/Judo-Xamarin <Judo-Xamarin@noreply.github.com>
CC: po0kie <marc@interpalma.com>; Author <author@noreply.github.com>
Asunto: Re: [JudoPay/Judo-Xamarin] Exception after clicking on "Pay" in JudoPay Page. Xamarin.Forms iOS (#45)


Hello Marc,
Thanks for getting in contact

Could you please provide with the exception type and message as well as details about your inputs. Obviously not card numbers but type of card (visa,Amex), type of payment could be helpful and I'll try and recreate the issue.

cheers
Luke

**Comment by LukeFieldsend** [comment]
Hey Marc,

by 'push modal' do you mean presenting a modal view in this fashion

[modal docs](https://developer.xamarin.com/api/member/Xamarin.Forms.INavigation.PushModalAsync/p/Xamarin.Forms.Page/)

the sdk presents a loading spinner after you press the pay butotn, by injecting an animated UIView

via this method 

```
private void ShowLoading (UIView view)
        {
            if (UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Pad) {
                _loadPop = new LoadingOverlay (new CGRect ((view.Frame.Width / 2) - 75f, (view.Frame.Height / 2) - 75f, 150f, 150f), true);
            } else {
                view = UIApplication.SharedApplication.Windows [0].RootViewController.View;
                _loadPop = new LoadingOverlay ();
                _loadPop.Frame = view.Frame;
            }
            view.Add (_loadPop);
        }

```
were LoadingOverlay is a subclassed UIView.

my guess is that in a Xamarin Forms modal view it is not getting 

 UIApplication.SharedApplication.Windows [0].RootViewController.View

or

 the initial passed in UIView correctly.

I will construct a small test app to investigate this theory myself but in the mean time

If you run the above code snippet substituting LoadingOverlay for an UIView

what is the result? we should be able to see which object is throwing a null

thanks for bringing this to my attention

Luke

**Comment by po0kie** [comment]
Hi Luke,

Exactly the RootViewController is null on Windows[0].

I have tried your code snipped.
And the Windows collection haves the following items:

? UIApplication.SharedApplication.Windows
{UIKit.UIWindow[3]}
    [0]: {UIKit.UIWindow}
    [1]: {UIKit.UIWindow}
    [2]: {UIKit.UIWindow}

Evaluating them:

? UIApplication.SharedApplication.Windows[0].RootViewController
(null)

? UIApplication.SharedApplication.Windows[1].RootViewController
{<Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x7fedc6d582f0>}
    base: {UIKit.UIViewController}
    Platform: {Xamarin.Forms.Platform.iOS.Platform}

? UIApplication.SharedApplication.Windows[2].RootViewController
{<UIInputWindowController: 0x7fedc6467000>}
    base: {UIKit.UIResponder}


Some work around for that?

Best regards
Marc

**Comment by LukeFieldsend** [comment]
Hey Marc,

The sdk was written initially without full forms support so we find issues like this from time to time (ever shrinking pool) we are currently entering into a project to provide full forms support to the sdk out of the box with no need for a service locator.

In the mean time I've come up with a fix for this issue and can provide you with dll's so you can move forward with development with the following disclaimer


### By agreeing to receive beta deliverables, you acknowledge and accept that said deliverables may contain unexpected issues due to the nature of the distribution.

### We endeavour to work closely with you to resolve any such issues and explain any changes with transparency, but please ensure you perform your own quality assurance on these deliverables before use. 


If correct the change will be included with the next release of the SDK through the component store. 

if you email developersupport@judopayments.com with you're JudoID referencing this case. I will be able to send you the beta dll's today and we can see if this resolves the issue

thanks

Luke

**Comment by po0kie** [comment]
Hi Luke,

sent an email to developersupport@judopayments.com
subject:Issue JudoPay Xamarin.Forms SDK, Beta DLLs

Best regards
Marc

**Comment by po0kie** [comment]
Ok the Libs are fixing the issue.

**Comment by LukeFieldsend** [comment]
great, i'll notify you here when the fix has made a production release

**Comment by jamesgoodwin** [comment]
HI @po0kie,

The latest version of our Xamarin SDK (version 3.0) now includes support for Xamarin Forms out of the box. I believe your original issue will be resolved by updating to our latest SDK. Please let us know if you have any further issues integrating.

Thanks,
James
